# SPDX-License-Identifier: Apache-2.0
"""
Tests for vllm_mlx/server.py utility functions.

Generated by MiniMax-M2.5 via openclaw simulation, reviewed and fixed by Claude.
"""

from unittest.mock import MagicMock, patch

import numpy as np
import pytest

from vllm_mlx.api.models import FunctionCall, ToolCall
from vllm_mlx.engine.base import GenerationOutput

# ---------------------------------------------------------------------------
# _resolve_temperature / _resolve_top_p
# ---------------------------------------------------------------------------


class TestResolveTemperature:
    """Tests for _resolve_temperature function."""

    def test_request_value_takes_priority(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_temperature
        try:
            cfg.default_temperature = 0.8
            assert server._resolve_temperature(0.3) == 0.3
        finally:
            cfg.default_temperature = old

    def test_cli_default_over_fallback(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_temperature
        try:
            cfg.default_temperature = 0.8
            assert server._resolve_temperature(None) == 0.8
        finally:
            cfg.default_temperature = old

    def test_fallback_when_nothing_set(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_temperature
        try:
            cfg.default_temperature = None
            assert server._resolve_temperature(None) == server._FALLBACK_TEMPERATURE
        finally:
            cfg.default_temperature = old

    def test_zero_is_valid_request_value(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_temperature
        try:
            cfg.default_temperature = 0.8
            assert server._resolve_temperature(0.0) == 0.0
        finally:
            cfg.default_temperature = old


class TestResolveTopP:
    """Tests for _resolve_top_p function."""

    def test_request_value_takes_priority(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_p
        try:
            cfg.default_top_p = 0.95
            assert server._resolve_top_p(0.7) == 0.7
        finally:
            cfg.default_top_p = old

    def test_cli_default_over_fallback(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_p
        try:
            cfg.default_top_p = 0.95
            assert server._resolve_top_p(None) == 0.95
        finally:
            cfg.default_top_p = old

    def test_fallback_when_nothing_set(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_p
        try:
            cfg.default_top_p = None
            assert server._resolve_top_p(None) == server._FALLBACK_TOP_P
        finally:
            cfg.default_top_p = old


# ---------------------------------------------------------------------------
# get_usage
# ---------------------------------------------------------------------------


class TestGetUsage:
    """Tests for get_usage function."""

    def test_full_attributes(self):
        from vllm_mlx.server import get_usage

        output = GenerationOutput(
            text="hello",
            tokens=[1, 2],
            prompt_tokens=100,
            completion_tokens=50,
        )
        usage = get_usage(output)
        assert usage.prompt_tokens == 100
        assert usage.completion_tokens == 50
        assert usage.total_tokens == 150

    def test_default_values(self):
        from vllm_mlx.server import get_usage

        output = GenerationOutput(text="hello")
        usage = get_usage(output)
        assert usage.prompt_tokens == 0
        assert usage.completion_tokens == 0
        assert usage.total_tokens == 0

    def test_only_prompt_tokens(self):
        from vllm_mlx.server import get_usage

        output = GenerationOutput(text="x", prompt_tokens=200)
        usage = get_usage(output)
        assert usage.prompt_tokens == 200
        assert usage.total_tokens == 200

    def test_only_completion_tokens(self):
        from vllm_mlx.server import get_usage

        output = GenerationOutput(text="x", completion_tokens=75)
        usage = get_usage(output)
        assert usage.completion_tokens == 75
        assert usage.total_tokens == 75


# ---------------------------------------------------------------------------
# _inject_json_instruction
# ---------------------------------------------------------------------------


class TestInjectJsonInstruction:
    """Tests for _inject_json_instruction function."""

    def test_prepend_to_existing_system_dict(self):
        from vllm_mlx.server import _inject_json_instruction

        messages = [
            {"role": "system", "content": "You are helpful."},
            {"role": "user", "content": "Hello"},
        ]
        result = _inject_json_instruction(messages, "Respond in JSON.")

        assert result[0]["content"].startswith("Respond in JSON.\n\n")
        assert "You are helpful." in result[0]["content"]
        assert len(result) == 2

    def test_prepend_to_existing_system_object(self):
        from vllm_mlx.server import _inject_json_instruction

        class Msg:
            def __init__(self, role, content):
                self.role = role
                self.content = content

        messages = [Msg("system", "You are helpful."), Msg("user", "Hi")]
        result = _inject_json_instruction(messages, "JSON only.")

        assert result[0].content.startswith("JSON only.\n\n")
        assert "You are helpful." in result[0].content

    def test_create_system_when_missing(self):
        from vllm_mlx.server import _inject_json_instruction

        messages = [{"role": "user", "content": "Hello"}]
        result = _inject_json_instruction(messages, "Respond in JSON.")

        assert len(result) == 2
        assert result[0]["role"] == "system"
        assert result[0]["content"] == "Respond in JSON."

    def test_empty_messages(self):
        from vllm_mlx.server import _inject_json_instruction

        result = _inject_json_instruction([], "JSON.")
        assert len(result) == 1
        assert result[0]["content"] == "JSON."

    def test_does_not_mutate_list_length(self):
        """Original list should not gain/lose elements."""
        from vllm_mlx.server import _inject_json_instruction

        messages = [{"role": "user", "content": "Hi"}]
        result = _inject_json_instruction(messages, "JSON.")
        assert len(messages) == 1  # original unchanged
        assert len(result) == 2  # result has new system msg


# ---------------------------------------------------------------------------
# _append_tool_continuation_prompt
# ---------------------------------------------------------------------------


class TestAppendToolContinuationPrompt:
    """Tests for tool-result continuation prompt injection."""

    def test_appends_after_tool_result_when_tools_requested(self):
        from vllm_mlx.service.helpers import _append_tool_continuation_prompt

        messages = [
            {"role": "user", "content": "Build the app"},
            {"role": "assistant", "content": "", "tool_calls": []},
            {"role": "tool", "tool_call_id": "call_1", "content": "PASS"},
        ]
        result, added = _append_tool_continuation_prompt(messages, True)

        assert added is True
        assert result[-1]["role"] == "user"
        assert "call the next tool now" in result[-1]["content"]
        assert len(messages) == 3

    def test_does_not_append_without_tools(self):
        from vllm_mlx.service.helpers import _append_tool_continuation_prompt

        messages = [{"role": "tool", "content": "PASS"}]
        result, added = _append_tool_continuation_prompt(messages, False)

        assert added is False
        assert result is messages

    def test_does_not_append_unless_last_message_is_tool(self):
        from vllm_mlx.service.helpers import _append_tool_continuation_prompt

        messages = [{"role": "user", "content": "continue"}]
        result, added = _append_tool_continuation_prompt(messages, True)

        assert added is False
        assert result is messages

    def test_appends_after_converted_tool_result_user_message(self):
        from vllm_mlx.service.helpers import _append_tool_continuation_prompt

        messages = [{"role": "user", "content": "[Tool Result (call_1)]: PASS"}]
        result, added = _append_tool_continuation_prompt(messages, True)

        assert added is True
        assert result[-1]["role"] == "user"
        assert "Do not stop with only reasoning" in result[-1]["content"]

    def test_repeated_tool_call_gets_anti_loop_prompt(self):
        from vllm_mlx.service.helpers import _append_tool_continuation_prompt

        messages = [
            {
                "role": "assistant",
                "tool_calls": [
                    {
                        "type": "function",
                        "function": {
                            "name": "read",
                            "arguments": '{"filePath":"app.ts","offset":10}',
                        },
                    }
                ],
            },
            {"role": "tool", "tool_call_id": "call_1", "content": "lines"},
            {
                "role": "assistant",
                "tool_calls": [
                    {
                        "type": "function",
                        "function": {
                            "name": "read",
                            "arguments": '{"offset":10,"filePath":"app.ts"}',
                        },
                    }
                ],
            },
            {"role": "tool", "tool_call_id": "call_2", "content": "same lines"},
        ]
        result, added = _append_tool_continuation_prompt(messages, True)

        assert added is True
        assert "Do not call the same tool" in result[-1]["content"]

    def test_repeated_bash_command_gets_anti_loop_prompt(self):
        from vllm_mlx.service.helpers import _append_tool_continuation_prompt

        messages = [
            {
                "role": "assistant",
                "tool_calls": [
                    {
                        "type": "function",
                        "function": {
                            "name": "bash",
                            "arguments": '{"cmd":"npm run test 2>&1 | tail -100"}',
                        },
                    }
                ],
            },
            {"role": "tool", "tool_call_id": "call_1", "content": "npm error"},
            {
                "role": "assistant",
                "tool_calls": [
                    {
                        "type": "function",
                        "function": {
                            "name": "bash",
                            "arguments": '{"cmd":"npm run test 2>&1 | tail -100"}',
                        },
                    }
                ],
            },
            {"role": "tool", "tool_call_id": "call_2", "content": "npm error"},
        ]
        result, added = _append_tool_continuation_prompt(messages, True)

        assert added is True
        assert "Do not call the same tool" in result[-1]["content"]

    def test_repeated_read_after_mutating_tool_uses_normal_prompt(self):
        from vllm_mlx.service.helpers import _append_tool_continuation_prompt

        messages = [
            {
                "role": "assistant",
                "tool_calls": [
                    {
                        "type": "function",
                        "function": {
                            "name": "read",
                            "arguments": '{"filePath":"app.ts"}',
                        },
                    }
                ],
            },
            {"role": "tool", "tool_call_id": "call_1", "content": "old"},
            {
                "role": "assistant",
                "tool_calls": [
                    {
                        "type": "function",
                        "function": {
                            "name": "edit",
                            "arguments": '{"filePath":"app.ts"}',
                        },
                    }
                ],
            },
            {"role": "tool", "tool_call_id": "call_2", "content": "edited"},
            {
                "role": "assistant",
                "tool_calls": [
                    {
                        "type": "function",
                        "function": {
                            "name": "read",
                            "arguments": '{"filePath":"app.ts"}',
                        },
                    }
                ],
            },
            {"role": "tool", "tool_call_id": "call_3", "content": "new"},
        ]
        result, added = _append_tool_continuation_prompt(messages, True)

        assert added is True
        assert "Do not stop with only reasoning" in result[-1]["content"]


# ---------------------------------------------------------------------------
# _extract_token_logprob
# ---------------------------------------------------------------------------


class TestExtractTokenLogprob:
    """Tests for _extract_token_logprob function."""

    def _make_logprobs(self, vocab_size=100, token_logprobs=None):
        """Create a mock mx.array with specific token logprobs."""
        arr = np.full(vocab_size, -10.0)  # low default
        if token_logprobs:
            for tid, lp in token_logprobs.items():
                arr[tid] = lp
        mock = MagicMock()
        mock.astype.return_value = mock
        return mock, arr

    def test_basic_top_k(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(100, {5: -0.1, 10: -0.5, 20: -1.0})
        tok = MagicMock()
        tok.decode.side_effect = lambda ids: f"t{ids[0]}"

        with patch("numpy.array", return_value=arr):
            result = _extract_token_logprob(mock, token_id=5, tokenizer=tok, top_k=3)

        assert result.token == "t5"
        assert result.logprob == pytest.approx(-0.1)
        assert len(result.top_logprobs) == 3
        # Sorted descending
        lps = [t.logprob for t in result.top_logprobs]
        assert lps == sorted(lps, reverse=True)

    def test_top_k_capped_at_vocab(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(10)
        tok = MagicMock()
        tok.decode.return_value = "x"

        with patch("numpy.array", return_value=arr):
            result = _extract_token_logprob(mock, token_id=0, tokenizer=tok, top_k=100)
        assert len(result.top_logprobs) == 10

    def test_out_of_bounds_token_id(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(100)
        tok = MagicMock()
        tok.decode.return_value = "x"

        with patch("numpy.array", return_value=arr):
            result = _extract_token_logprob(mock, token_id=500, tokenizer=tok, top_k=3)
        assert result.logprob == 0.0

    def test_bytes_field_populated(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(100, {5: -0.1})
        tok = MagicMock()
        tok.decode.return_value = "hello"

        with patch("numpy.array", return_value=arr):
            result = _extract_token_logprob(mock, token_id=5, tokenizer=tok, top_k=1)
        assert result.bytes == list(b"hello")

    def test_astype_called_for_conversion(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(10)
        tok = MagicMock()
        tok.decode.return_value = "x"

        with patch("numpy.array", return_value=arr):
            _extract_token_logprob(mock, token_id=0, tokenizer=tok, top_k=1)
        mock.astype.assert_called_once()


# ---------------------------------------------------------------------------
# _validate_tool_call_params
# ---------------------------------------------------------------------------


class TestValidateToolCallParams:
    """Tests for _validate_tool_call_params function."""

    def _make_tools(self, name="get_weather", properties=None):
        if properties is None:
            properties = {"location": {"type": "string"}}
        return [
            {
                "type": "function",
                "function": {
                    "name": name,
                    "parameters": {
                        "type": "object",
                        "properties": properties,
                    },
                },
            }
        ]

    def _make_tool_calls(self, name="get_weather", arguments='{"location": "NYC"}'):
        return [
            ToolCall(
                id="call_1",
                type="function",
                function=FunctionCall(name=name, arguments=arguments),
            )
        ]

    def test_valid_args_no_error(self):
        from vllm_mlx.server import _validate_tool_call_params

        _validate_tool_call_params(
            self._make_tool_calls(),
            self._make_tools(),
        )

    def test_invalid_json_no_crash(self):
        from vllm_mlx.server import _validate_tool_call_params

        _validate_tool_call_params(
            self._make_tool_calls(arguments="not json {"),
            self._make_tools(),
        )

    def test_type_mismatch_no_crash(self):
        from vllm_mlx.server import _validate_tool_call_params

        _validate_tool_call_params(
            self._make_tool_calls(arguments='{"location": 123}'),
            self._make_tools(properties={"location": {"type": "string"}}),
        )

    def test_enum_violation_no_crash(self):
        from vllm_mlx.server import _validate_tool_call_params

        _validate_tool_call_params(
            self._make_tool_calls(arguments='{"unit": "kelvin"}'),
            self._make_tools(
                properties={
                    "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                }
            ),
        )

    def test_empty_tool_calls(self):
        from vllm_mlx.server import _validate_tool_call_params

        _validate_tool_call_params([], self._make_tools())

    def test_pydantic_model_tools(self):
        """Test with Pydantic model tools (have model_dump)."""
        from pydantic import BaseModel

        from vllm_mlx.server import _validate_tool_call_params

        class ToolDef(BaseModel):
            type: str = "function"
            function: dict

        tools = [
            ToolDef(
                function={
                    "name": "get_weather",
                    "parameters": {
                        "type": "object",
                        "properties": {"location": {"type": "string"}},
                    },
                }
            )
        ]
        _validate_tool_call_params(
            self._make_tool_calls(),
            tools,
        )


# ---------------------------------------------------------------------------
# extract_json_from_response guard tests
# ---------------------------------------------------------------------------


class TestExtractJsonFromResponse:
    """Tests for extract_json_from_response showing why guard is needed."""

    def test_extracts_json_from_reasoning_text(self):
        """Correctly extracts JSON from reasoning prefix."""
        from vllm_mlx.api.utils import extract_json_from_response

        text = 'Let me think... {"result": 42}'
        assert extract_json_from_response(text) == '{"result": 42}'

    def test_corrupts_plain_text_ending_with_json(self):
        """Without guard, plain text ending with JSON-like braces gets corrupted.

        This documents why server.py wraps the call with `if response_format`.
        """
        from vllm_mlx.api.utils import extract_json_from_response

        # Plain text that happens to end with balanced braces
        plain = 'The config looks like {"debug": true}'
        result = extract_json_from_response(plain)
        # The function extracts '{"debug": true}' — losing the prefix
        assert result == '{"debug": true}'
        assert result != plain

    def test_returns_original_when_no_json(self):
        """Returns original text when no JSON structure found."""
        from vllm_mlx.api.utils import extract_json_from_response

        text = "Hello, world!"
        assert extract_json_from_response(text) == text
